### ISSUE TITLE
请问data/nlp7294/目录中的数据集是什么

### ISSUE THREAD

**Issue by Dioxideme** [hiyoung123/SoftMaskedBert#9]
def load_toutiao_dataset2():
    dataset = []
    file_path = 'data/nlp7294/'
    for file in os.listdir(file_path):
        index = -1
        with open(file_path+file, 'r') as f:
            for line in f:
                index += 1
                if index == 0:
                    continue
                line = line.strip().split()[1]
                dataset.append(line)
    return dataset

**Comment by wjy3326** [comment]
数据集可以分享下嘛？

**Comment by Dioxideme** [comment]
> 数据集可以分享下嘛？

你好，我目前也只找到了toutiao_cat_data.txt这个数据集，地址在https://github.com/skdjfla/toutiao-text-classfication-dataset。如果您找到了其他数据集，也请分享下。

**Comment by wjy3326** [comment]
嗯嗯，谢谢，可是这是文本分类数据集？不是纠错数据集啊，可以用于文本纠错吗，我主要是形近字的纠错。那你做纠错模型是用的这个数据集吗？https://github.com/shibing624/pycorrector&nbsp;这个GitHub上有一个nlpcc 数据集，但是是.src格式，我不知道怎么读取，你看一下，如果你会读取，麻烦告诉我哈，那个加个微信吧，你也是做文本纠错吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dioxideme"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 下午5:56
收件人:&nbsp;"hiyoung123/SoftMaskedBert"<SoftMaskedBert@noreply.github.com&gt;;
抄送:&nbsp;"王俊艳"<1079158605@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hiyoung123/SoftMaskedBert] 请问data/nlp7294/目录中的数据集是什么 (#9)





  
数据集可以分享下嘛？
  
你好，我目前也只找到了toutiao_cat_data.txt这个数据集，地址在https://github.com/skdjfla/toutiao-text-classfication-dataset。如果您找到了其他数据集，也请分享下。

**Comment by Dioxideme** [comment]
> 嗯嗯，谢谢，可是这是文本分类数据集？不是纠错数据集啊，可以用于文本纠错吗，我主要是形近字的纠错。那你做纠错模型是用的这个数据集吗？[https://github.com/shibing624/pycorrector&nbsp;这个GitHub上有一个nlpcc](https://github.com/shibing624/pycorrector&nbsp;%E8%BF%99%E4%B8%AAGitHub%E4%B8%8A%E6%9C%89%E4%B8%80%E4%B8%AAnlpcc) 数据集，但是是.src格式，我不知道怎么读取，你看一下，如果你会读取，麻烦告诉我哈，那个加个微信吧，你也是做文本纠错吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Dioxideme"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月24日(星期三) 下午5:56 收件人:&nbsp;"hiyoung123/SoftMaskedBert"<SoftMaskedBert@noreply.github.com&gt;; 抄送:&nbsp;"王俊艳"<1079158605@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [hiyoung123/SoftMaskedBert] 请问data/nlp7294/目录中的数据集是什么 (#9) 数据集可以分享下嘛？ 你好，我目前也只找到了toutiao_cat_data.txt这个数据集，地址在[https://github.com/skdjfla/toutiao-text-classfication-dataset。如果您找到了其他数据集，也请分享下。](https://github.com/skdjfla/toutiao-text-classfication-dataset%E3%80%82%E5%A6%82%E6%9E%9C%E6%82%A8%E6%89%BE%E5%88%B0%E4%BA%86%E5%85%B6%E4%BB%96%E6%95%B0%E6%8D%AE%E9%9B%86%EF%BC%8C%E4%B9%9F%E8%AF%B7%E5%88%86%E4%BA%AB%E4%B8%8B%E3%80%82) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

这个项目的load_toutiao_dataset1()函数就是使用的该数据集来生成错误数据用于纠错。

**Comment by wjy3326** [comment]
我找到那个数据集了，给你发不过去，你加我微信吧，mxl20130523


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dioxideme"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 晚上6:08
收件人:&nbsp;"hiyoung123/SoftMaskedBert"<SoftMaskedBert@noreply.github.com&gt;;
抄送:&nbsp;"王俊艳"<1079158605@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hiyoung123/SoftMaskedBert] 请问data/nlp7294/目录中的数据集是什么 (#9)





  
嗯嗯，谢谢，可是这是文本分类数据集？不是纠错数据集啊，可以用于文本纠错吗，我主要是形近字的纠错。那你做纠错模型是用的这个数据集吗？https://github.com/shibing624/pycorrector&nbsp;这个GitHub上有一个nlpcc 数据集，但是是.src格式，我不知道怎么读取，你看一下，如果你会读取，麻烦告诉我哈，那个加个微信吧，你也是做文本纠错吗？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Dioxideme"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月24日(星期三) 下午5:56 收件人:&nbsp;"hiyoung123/SoftMaskedBert"<SoftMaskedBert@noreply.github.com&gt;; 抄送:&nbsp;"王俊艳"<1079158605@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [hiyoung123/SoftMaskedBert] 请问data/nlp7294/目录中的数据集是什么 (#9) 数据集可以分享下嘛？ 你好，我目前也只找到了toutiao_cat_data.txt这个数据集，地址在https://github.com/skdjfla/toutiao-text-classfication-dataset。如果您找到了其他数据集，也请分享下。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
这个项目的load_toutiao_dataset1()函数就是使用的该数据集来生成错误数据用于纠错。

**Comment by BigWavelet** [comment]
nlp7294dataset估计是[这个](https://www.kesci.com/home/dataset/5dd645fca0cb22002c94e65d/files)  ？

**Comment by lx3528** [comment]
新闻标题短文本分类 | 2019年12月 | chenfengshf
-- | -- | --
https://www.kesci.com/mw/dataset/5dd645fca0cb22002c94e65d/file

**Comment by 13239543393** [comment]
这个数据集

> 新闻标题短文本分类	2019年12月	chenfengshf
> https://www.kesci.com/mw/dataset/5dd645fca0cb22002c94e65d/file
这个数据集的是哪儿的呀 ，我有这个数据集 但是下载时间过长 找不到数据集来源
